//não é mais necessário passar um parametro no catch
// try{
// throw('Houve um erro')
// }catch(e){
//  console.log(e)
// }
try{
    throw('Houve um erro')
    }catch{
     console.log('Chegamos no erro')
    }